### ISSUE TITLE
SpeedShare auto update question

### ISSUE THREAD

**Issue by MRColorR** [MRColorR/speedshare#1]
Hello, and thank you for your amazing work on this project. I've been exploring the image and have some thoughts and questions that might help enhance it further:

- It appears the app's installation occurs at runtime via the entrypoint, ensuring the latest version upon first run. However, this approach seems to bypass updates for existing instances and causes a new device to appear on every restart. Could an alternative method ensure continuous updates without sacrificing the benefits of your current strategy?
  - I've noticed potential issues with the device UUID changing with each image update, potentially cluttering the dashboard with multiple device entries. Would it be feasible to allow a persistent UUID through an environment variable for consistency?
- For updates and to install the app direcly in the image building phase, perhaps implementing an MD5 checksum in the GitHub Actions could automate version checks and updates (download app check md5sum if different from the saved one then procees with installing and building steps), pushing these directly to Docker Hub, ready to use.
  - Lastly, as an alternative, considering the speedshare CLI's update command, might there be a way to incorporate automatic updates within running containers, maybe through a scheduled task or similar mechanism this is suboptimal for containers but worth exploring)

These are just some initial thoughts. I'm looking forward to hearing your insights and discussing potential improvements

**Comment by ElDavoo** [comment]
> Hello, and thank you for your amazing work on this project. 

Thanks to you for the amazing money4band project! The speedshare container is a direct result of seeing the websites supported by your project.  

> 
> These are just some initial thoughts. I'm looking forward to hearing your insights and discussing potential improvements

All you said is true, but I don't want to spend time on this project (for now), I don't consider it important (even because the payout from my area is really minimal). I will accept PRs or if you're happy with that I can transfer the ownership of the project :)

**Comment by MRColorR** [comment]
> > Hello, and thank you for your amazing work on this project. 
> 
> Thanks to you for the amazing money4band project! The speedshare container is a direct result of seeing the websites supported by your project.  
> 
> > 
> > These are just some initial thoughts. I'm looking forward to hearing your insights and discussing potential improvements
> 
> All you said is true, but I don't want to spend time on this project (for now), I don't consider it important (even because the payout from my area is really minimal). I will accept PRs or if you're happy with that I can transfer the ownership of the project :)
> 
> 

Thank you for your response and for considering my suggestions. I'm honored that my project inspired you and i'm even more honored by the opportunity to contribute more significantly to the project. Given your current stance, I would be glad to take on a more active role, accepting the ownership transfer. This project has great potential, and I'm excited about the prospect of enhancing it further with you. Let's coordinate the next steps for a smooth transition and collaboration. Thanks again for your openness and trust i really appreciate it.

**Comment by ElDavoo** [comment]
OK, you'll need to delete your fork first

**Comment by MRColorR** [comment]
> OK, you'll need to delete your fork first

Ok, i've deleted it.

As a token of appreciation for your contributions and to honor your role in this project's development, I'd like to give you the contributors role within the Money4Band Discord community. Let me know if this aligns with your interest too.

**Comment by ElDavoo** [comment]
Sounds right! Transfer requested.
