### ISSUE TITLE
can't connect to server ,print "server unavailable" log

### ISSUE THREAD

**Issue by 78chicken** [MRColorR/speedshare#3]
any one had same error ?
```
time="Jul 02 15:21:08" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
time="Jul 02 15:22:01" level=info msg="SpeedShare Server unavailable (P) (A)" service=speedshare-cli
```

**Comment by ElDavoo** [comment]
yep

**Comment by MRColorR** [comment]
hello and thank you for reaching out. i'll take a look at this soon

**Comment by MRColorR** [comment]
Thank you for your patience. I've done some research and tests and i can confirm the following:
- the image is updated and there are no updates from speedshare
- the connection parameters are not changed ATM but the connection continue to fail (tried also to manually connect) 
  - this seems a speedshare server side problem and from what i've read on thier discord the speedshare dev is aware of that.
- on their DS server i've found the following message:
 "Packet is aware or the issue with SpeedShare's server. Problem is that he also has other problems alongside that to fix and surely some personal issues. We will keep you guys updated if the server stays down after a while. Thank you for taking your time to read this."
- currently all the payments method are disabled

So i think for now the image is fine by our side but we have to wait and see how it goes
